name:        binary-tree
version:     0.1.0.0
github:      "carp-sushi/binary-tree"
license:     BSD3
author:      "carp-sushi"
maintainer:  "105142707+carp-sushi@users.noreply.github.com"
copyright:   "Copyright 2022-present, the original author(s)"
description: Please see the README on GitHub at <https://github.com/carp-sushi/binary-tree#readme>

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

#ghc-options:
#- -Wall
#- -Wcompat
#- -Widentities
#- -Wincomplete-record-updates
#- -Wincomplete-uni-patterns
#- -Wmissing-export-lists
#- -Wmissing-home-modules
#- -Wpartial-fields
#- -Wredundant-constraints

library:
  source-dirs: src

executables:
  binary-tree-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - binary-tree

tests:
  binary-tree-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - binary-tree
    - hspec
    - tasty
    - tasty-hspec
    - ascii-char
